version: '3'

services:
  mariadb:
    build:
      context: ./mariadb/
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"

volumes:
  

networks:
  honeycomb: