version: '3'

services:

  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      args:
       - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
       - MYSQL_USER=$MYSQL_USER
       - MYSQL_PASSWORD=$MYSQL_PASSWORD
       - MYSQL_WP_NAME=$MYSQL_WP_NAME
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    ports:
      - "3306:3306"
    restart: always

networks:
  inception:

volumes:
  mariadb_vol:
    driver: local
